name: PGE → Trello (daily)

on:
  schedule:
    - cron: '5 5 * * *'  # codziennie ~07:05 CET/CEST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout (empty)
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm i
          npx playwright install --with-deps chromium

      - name: Run
        env:
          TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          BOARD_ID: ${{ secrets.BOARD_ID }}
          LIST_RZESZOW_ID: ${{ secrets.LIST_RZESZOW_ID }}
          LIST_SKARZYSKO_ID: ${{ secrets.LIST_SKARZYSKO_ID }}
        run: node index.js
